### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by ahmeterbay** [dgngulcan/droid-feed#7]
i design logo/icon for "open source projects" on utopian .. 
i thınk your project need a good logo whıch make your applıcatıon vıew better..
wanna me desıgn a logo "free" for your applıcatıon?

please reply my post... ı ll start do design and share with you and than send a post on website  "utopian.io"..
also u can connect wıth me on discord "@ahmeterbay" or emaıl "ahmeterbay@gmail.com"

i did a design for your application.. plss feedback me :)

![untitled-23](https://user-images.githubusercontent.com/33961326/37559778-c7a4bae2-2a3c-11e8-8fc7-c5a894cd799f.png)

**Comment by dgngulcan** [comment]
Hi Ahmet, thank you for the contribution! 
Unfortunately, we decided to stick with the current one because it fits with the app's overall visual design. There are cases where the icon is displayed as small as 48px and I am concerned that the one you created might look too complex for the size. 

Thanks again for the contribution!
